# Generated by Django 2.1.5 on 2021-02-19 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimcategory',
            name='name',
            field=models.CharField(choices=[('Motor Claim', 'Motor Claim'), ('Life Claim', 'Life Claim')], max_length=200),
        ),
    ]
