# Generated by Django 2.1.5 on 2021-02-19 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_categoryclaim'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoryClaim',
            new_name='ClaimCategory',
        ),
        migrations.AlterModelOptions(
            name='claimcategory',
            options={'verbose_name_plural': 'ClaimCategory'},
        ),
    ]
