# Generated by Django 2.1.5 on 2021-02-19 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210219_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Category'),
        ),
    ]
